### PR TITLE
Blender functions

### PR DESCRIPTION
**Pull request by gsohler**
Hi Doug,

I added a function "blender functions.curv" where I added all the blender functions found on mercury.
Most of them are working. some look weird. Grid display function is also included.
They follow the latest code style suggestion sent by you. Would be nice to have them available by default.

### CODE REVIEW

**Comment by gsohler** [comment]
Hi doug,

I like the idea very much combining the blender arguments into one argument set as effectively each blender function has a different number of arguments and engrave e.g. is even compromised

However, when i try to implement your changes i dont get the syntax correctly anymore.

I tried several permuations of:

stairs ( 0.5,3 ) .union (sphere, cube >> move(1,1,1)) 

ERROR: .union: not defined

put none of them is satisfying for curv. How to get that correct ?

**Comment by doug-moen** [comment]
1. Try typing stairs ( 0.5,3 ) and see if the output gives you any ideas.

2. Show me the code that isn't working. Otherwise I have no idea what the problem is.

**Comment by gsohler** [comment]
Doug,
it did not take me much to find out that i cannot proceed.
Introducing the paranthesis i could not get it clean anymore.
I tried with (0.5,3) , (0.5 3) , [0.5, 3]  and some others.

Can you fix this one syntax error for me, then i can proceed myself.

Guenther



[blender_functions.txt](https://github.com/doug-moen/curv/files/2350183/blender_functions.txt)

**Comment by doug-moen** [comment]
Your program contains this code:

let

make_blend config r n = {

We had discussed changing it to 'make_blend config arg = { ...', so that it
isn't necessary to always pass two separate arguments to a blending kernel.

stairs is defined as
stairs = make_blend { ... };

If you just type 'stairs' with no arguments, you get 'make_blend _', which
is a partially applied call to the function 'make_blend', with only one
argument (the config argument) specified. 'stairs' needs two more
arguments, 'r' and 'n'. If you just type 'stairs (0.5, 3)', then you have
supplied the 'r' argument, but 'n' is still missing, so you get another
partially applied function that prints as 'make_blend _ _'.

By the way, this is helping me think about how Curv could print better
error messages, so thanks for that opportunity.

**Comment by gsohler** [comment]
Hi Doug,
I was able to improve all code for having variable parameter lengths for different blender functions.
Even the tongue and engrave function has the correct number of arguments.
Everthing is checked in. 
Most of the blender functions are working.
some of them are annoteted: "have a problem" . they appear to be inside-out
Tell me, what you think

**Comment by gsohler** [comment]
Sorry doug, wrong me.
I was inspired by the mercury code haveing there sqrt(2).  My intent was that the 45deg section of the chamfer would be the dimenstion specified, so the cathetes would by smaller by a factor of sqrt(2).
i put this factor without furrhter thinking, nor closer looking this "interesting" V- like  blender function.
The Error is corrected already.

**Comment by doug-moen** [comment]
Columns doesn't work right now so I can't test it.
```
columns_union = make_blend {
    fmin (a, b, r, n) =
```
`fmin` should be declared with `(a,b,(r,n))` as the parameter pattern.

**Comment by doug-moen** [comment]
Why are columns_union and columns_intersection declared separately? I guess it's because the 'max' function for columns cannot be derived from the 'min' function.

To fix this, we can change `make_blend` so that the `config` argument can optionally define an `fmax` function.

`make_blend` currently looks like this:
```
make_blend config args = {
    union (s1,s2) = ...;
    intersection (s1,s2) = ...;
    difference (s1,s2) = ...;
    bmin(a,b) = ...;
    bmax(a,b) = ...;
};
```
First, change all of the `=` definitions to `:` statements inside of the { ... } body of make_blend. Like this:
```
make_blend config args = {
    union (s1,s2) : ...;
    intersection (s1,s2) : ...;
    difference (s1,s2) : ...;
    bmin(a,b) : ...;
    bmax(a,b) : ...
};
```
Then, change the definition of `bmax` to look like this:
```
    if (defined(config.fmax))
        bmax(a,b) : config.fmax(a, b, args);
    else
        bmax(a,b) : -config.fmin(-a, -b, args);
```
And now we can define columns using
```
columns = make_blend {
    fmin(a, b, (r, n)) = ...;
    fmax(a, b, (r, n)) = ...;
};
```

**Comment by gsohler** [comment]
Hi doug
Thank you for your explaination. I look forward to see the blender function becoming a particular part and easy-to-use functionality of curv.
However, it does not yet work.
Following your instructions to get from a "="syntax to an ":"syntax does not work.
Always get different errors. right now, it tells me: bmin is not defined and i also tried puting the bmin definition to the top. (have been trying many different options during the day and none of them succeeded)

Whats wrong with my code ?

**Comment by doug-moen** [comment]
Hi Guenther. I gave you bad advice in my last message. That code indeed does not work. I should have tested it before suggesting you try it. I am now trying to figure out an alternate strategy.

**Comment by doug-moen** [comment]
I pushed a new version of make_blend to your repository on github. Now there is a single blending kernel called 'columns'. The output looks approximately correct, similar to the images on Mercury.sexy. However, the distance field is bad.

**Comment by doug-moen** [comment]
The last 4 operators, called `pipes`, `engrave`, `groove` and `tongue`, are not blending kernels with `.union`, `.intersection` and `.difference` variants. So you should not be using `make_blend` to define them. For example, the interface to `pipes` should look like this:
```
pipes  0.2 (sphere, cube >> move(1,1,1))
```

**Comment by gsohler** [comment]
Hi Doug, of course the "union" info for pipes is extra and can be skipped in a nice syntaxxed library.
For me its just not as easy to implement this.
I have starting deriving a simplified blender, which only contains the union, but i cannot remove the " union"hierarchy". its not yet syntax clean.
In order to succeed i need to understand the exact concept, how values map to function arguments in this quite "object oriented" approach to user the blender function.
I tried to read several chapters of the doc e.g. records, functions, grammar. But i am not yet clear, how the parameters map exactly.
e.g. its clear that for stairs, '3' maps to n
but in my latest checkin, blender_simplified does not know s1 and s2 and i dont know at which exact place in the function definition i need to install the receptor so the function can capture it.

Can you point me to the best rst file in your doc directory, which explains it ?

**Comment by doug-moen** [comment]
I think you want to read a tutorial on the basics of functional programming in Curv. I don't have anything like that in the documentation right now. It's something I know that we need.

Try this:
```
make_blend_simple config args (s1,s2) =
    make_shape {
```

For something simple like `pipes`, you could also implement it directly, like this:
```
pipes r (s1, s2) =
    make_shape {
        dist p = mag(s1.dist p, s2.dist p) - r;
        ...
```

**Comment by doug-moen** [comment]
Try this:
```
engrave  0.2 (sphere>>colour red, cube >> move(1,1,1))
```
The colours are wrong. It should be all red.

This is similar to a difference operation, where the cube is used to specify what to remove from the sphere. So the colour should only come from the sphere, as it does in a difference (or intersection) operation.

I think the same is true for all of the non-blending operations: pipes, engrave, tongue, groove.

You should define the colour to be the same as s1.colour, like this:
```
    colour = s1.colour;
```
The same code is used by `make_blend` to define the colour for an intersection.

**Comment by doug-moen** [comment]
Here is an example of an incorrect bounding box.
```
engrave  0.2 (circle>>colour red, square >> move(1,1)) >> show_bbox
```
This bounding box is too large, since it encloses both the circle and the square (s1 and s2).

Since `engrave` just removes material from s1, it would be appropriate to define the bounding box to be equal to `s1.bbox`. This might be too large, but it is a good approximation.

**Comment by doug-moen** [comment]
`tongue` doesn't work. Here is the definition:
```
tongue = make_blend_simple {
    fmin (a, b, ra, rb) =
    min(a,max(a-ra,abs(b)-rb));
};
```
It should be defined as
```
tongue = make_blend_simple {
    fmin (a, b, (ra, rb)) =
    min(a,max(a-ra,abs(b)-rb));
};
```

**Comment by doug-moen** [comment]
With the corrected version of `tongue`, here is an example of a bad bounding box:
```
tongue (0.2,0.1) (circle, square) >> show_bbox
```
The bounding box is too small to contain the shape, so when you run this program, you have to zoom out to see the entire shape. The parts of the shape that stick out of the bounding box are coloured in red.

**Comment by doug-moen** [comment]
I suggest you get rid of make_blend_simple, and just define the non-blend operators directly. The reason is: I think that the bbox definition needs to be different for each of the 4 operators. Once you define the bbox separately for each operator, there is little code duplication between the 4 operators, and make_blend_simple isn't providing much benefit.

For example, consider this definition of `pipes`:
```
let
pipes r (s1, s2) =
    make_shape {
        dist p = mag(s1.dist p, s2.dist p) - r;
        colour = s1.colour;
        bbox = [ max(s1.bbox[MIN], s2.bbox[MIN]) - r,
                 min(s1.bbox[MAX], s2.bbox[MAX]) + r ];
        is_2d = s1.is_2d && s2.is_2d;
        is_3d = s1.is_2d && s2.is_2d;
    };
in
pipes 0.2 (circle, square >> move(1,1)) >> show_bbox
```
I think this code is pretty clear.

An alternative is to add a bbox function to the config record of make_blend_simple, for computing the bbox from arg.

**Comment by gsohler** [comment]
Hi Doug,

Your proposal works like a charm!
I have coded all 4 extra functions now and checked them in.

Günther

**Comment by gsohler** [comment]
Hi Doug,

in fact all the ordinary blending operators did have a wrong bbox.
I have rewritten the bbox expression. in fact now it only uses one line of code instead of two.
Now the bbox appears correct. was the problem really with the line break or is there another issue i did not find ?

**Comment by gsohler** [comment]
Doug,

I was wrong with my assumption ,that after removing the line break the code becomes correct.
When I removed the line break and it was correct, but it was correct before.

All your 4 Testcase are extreme cases blending a object with a object of the exact same shape.
Normally the blender functions render some special "shape" at the transition between the object.
In your case of the chamfer or the round its raised by 0.5.

In your special case the objects are equal and the transition happens everywhere, thus the object is raised everywhere.
Both objects beeing equal is definetly not a case where a user would use a blending function for and just enlarging the bbox by 0.5 so the result is correct in 0.00001% and overcorrect 99.9999% is not something what we should implement. I suggest  this is not a bug ;)

P.S in normal cases the objects are apart by more than 0.5 and the input objects bboxes are dominant in the max functions in contrast to the raising in the transition. so the bbox ' as is'  is correct

**Comment by doug-moen** [comment]
In cases like this (blending functions), the bounding box is an approximation. If the bounding box is too large, nothing bad happens. If the bounding box is too small, then:
* in 2D, the default view will not show the entire shape (the edges are cut off, until you zoom out)
* in 3D, if you export the object as STL for 3D printing, then the edges are cut off

So it is best if the bounding box is large enough to handle every case.

These blending functions have the property that you can get "bulges", and it's not difficult to encounter this situation. The bulges stick out of the currently defined bounding box. The trick of unioning a shape with itself is just a guaranteed way to force a "bulge" to occur, for testing purposes.

For example, check out this model on shadertoy: https://www.shadertoy.com/view/MsXGWr

Notice the bulges at the elbow and knee? Those bulges are created by smooth union operator. You see them if you butt two objects together. So the bulge can occur in practice, and it needs to be accounted for.

**Comment by gsohler** [comment]
you are right.
you can also easy create those bulgs in curv
let
caps=capsule{d:0.5, from:[0,0,0],to:[1,0,0] }
in
chamfer .5 .union(caps,caps >> rotate(3.14))  >> show_bbox

i checked in my modified bbox with accounts for this extreme.
However, i have coded a fixed value of 0.5 because i cannot extract the amount of bulg from the parameters(and there are several forms)

Günther

**Comment by doug-moen** [comment]
A fixed value of 0.5 is a start, but we will need a more general solution.

First, recall that dist(x,y,z,t) computes the distance of the point (x,y,z) from the boundary of the shape at time t. This distance value is 0 on the boundary of the shape, negative inside the shape, and positive outside the shape.

Let's consider smooth union. The fmin function for smooth union is
```
    fmin (a, b, r) =
        let
        h = clamp( 0.5+0.5*(b-a)/r, 0, 1 );
        in lerp( b, a, h ) - r*h*(1.0-h);
```
Consider the case where we smooth union two identical circles.
```
smooth r .union (circle, circle)
```
At the boundary of the input circle, the distance field has the value 0. So `a` and `b` in `fmin` will be zero. Substituting `a=0` and `b=0` into fmin, we get:
```
        let
        h = clamp( 0.5+0.5*(0-0)/r, 0, 1 );
        in lerp( 0, 0, h ) - r*h*(1.0-h)
```
* `h = clamp( 0.5+0.5*(0-0)/r, 0, 1 );`
* `h = clamp( 0.5+0.5*0/r, 0, 1 );`
* `h = clamp( 0.5+0/r, 0, 1 );`
* `h = clamp( 0.5, 0, 1 );`
* `h = 0.5;`
* `in lerp( 0, 0, h ) - r*h*(1.0-h)`
* `in lerp( 0, 0, 0.5 ) - r*0.5*(1.0-0.5)`
* `in 0 - r*0.5*(1.0-0.5)`
* `in 0 - r*0.5*0.5`
* `in 0 - r*0.25`
* `-r/4`

So this means, at points on the boundary of the original input circle, the distance field for the smooth union will have the value `-r/4`. If the distance field is accurate, this means that these points are a distance of r/4 units inside the boundary of the smooth union. So the "bulge" has a thickness of r/4, assuming the distance field is accurate.

To test this theory, I modified the bbox of smooth union in lib/std.lib by adding/subtracting a "bulge factor" of r/4. Tested it, and it works. I have pushed this change to your branch. Here is the test code:
```
smooth .5 .union (circle,circle) >> show_bbox
```

**Comment by doug-moen** [comment]
To perform some of these computations, you can use curv in interactive mode. Type the `curv` command with no arguments, and you get an interactive shell:
```
$ curv
curv> clamp( 0.5, 0, 1 )
0.5
curv> lerp( 0, 0, 0.5 )
0
```
Next things to figure out: Can `smooth .intersection` and `smooth .difference` create a bulge? What is a good test case for this? How do you fix the bbox?

**Comment by doug-moen** [comment]
The smooth intersection and smooth difference operations are like regular intersection and difference, except that they subtract some additional material from the result. In contrast to smooth union, which adds additional material to the result of a regular union.

For this reason, and based on some limited testing, I don't think that smooth intersection and smooth difference can create a bulge. So I think that no bbox adjustment is needed.

**Comment by doug-moen** [comment]
Next thing to figure out: what is the bulge expression for chamfer .union?

**Comment by doug-moen** [comment]
Note. I think each blending operator has its own bulge function. For `smooth`, the bulge function is:
```
bulge r = r/4
```

**Comment by doug-moen** [comment]
If the analysis I used for smooth union works for the other blending operators, then the bulge can be generically computed as `bulge = -bmin(0,0)`.

**Comment by doug-moen** [comment]
And that works fine for the following test cases:
```
//smooth 0.5 .union(circle, circle) >> show_bbox
//chamfer 0.5 .union(circle, circle) >> show_bbox
//stairs (0.5,3) .union(circle, circle) >> show_bbox
columns (0.5,3) .union(circle, circle) >> show_bbox
```

**Comment by doug-moen** [comment]
So I just pushed that change. Please look at the code and run some more tests, see if everything looks okay.

**Comment by gsohler** [comment]
its a great idea with the -bmin(0,0)

Thank you for implementing.
will do some tests ;)

**Comment by gsohler** [comment]
i have done quite some tests, rerun all my testcase, and made some experiments with the capsule and the bbox
even the tests which were marked "Problem" work with lipschitz now.
thank you for realizing the blending functions with me. without you i would have never mastered the syntax neither implemented object oriented approach

**Comment by doug-moen** [comment]
Thanks for all your hard work. I did some final cleanup and accepted the PR.

**Comment by gsohler** [comment]
Np. It was fun for me, too.

During taking a bath, I got an extra idea for a blender. I think its the easiest, when i just post it here:

gap g (s1, s2) =
    make_shape {
        dist p = let
		 a=s1.dist p;
		 b=s2.dist p;
                 d=if(a > g || b > g) min(a,b)
                 else -abs(a-b)+g
		 ;
		 in
		 d;
        colour = s1.colour;
        bbox = s1.bbox;
        is_2d = s1.is_2d && s2.is_2d;
        is_3d = s1.is_3d && s2.is_3d;
    };

gap 0.1 (sphere, sphere >> move(1,0,0) )

it has the same bbox like the union and works best for identical objects. Would you include my name into the blend.curv ?

**Comment by doug-moen** [comment]
I added credits to blend.curv

Your gap function is cool. I'm playing with it to see if I would be able to
use it in a model.

**Comment by doug-moen** [comment]
I modified the colour function in `gap`. Check out my model.
```
let
gap g (s1, s2) =
    make_shape {
        dist p =
            let a=s1.dist p;
                b=s2.dist p;
                d=if(a > g || b > g) min(a,b) else -abs(a-b)+g;
            in d;
        colour p =
            let d1 = s1.dist p;
                d2 = s2.dist p;
            in if (d1 <= d2) s1.colour p else s2.colour p;
        bbox = s1.bbox;
        is_2d = s1.is_2d && s2.is_2d;
        is_3d = s1.is_3d && s2.is_3d;
    };

in
gap 1.5
    ( sphere 33 >> colour (sRGB.HSV(0,.8,.8)),
      gyroid >> shell .2 `intersection` cube 30 )
  >> lipschitz 2
```

**Comment by gsohler** [comment]
Hi Doug,
Thank you for the credits.
Glad you like the new blender. I never considered using it in a concentric way, though ...
Great sponge :)

**Pull request merged**
