### PR TITLE
extending reset_view with more defaults

### PR DESCRIPTION
**Pull request by TLC123**
Yay first commit on github.
keys:
(R) for reset retired  leaving HOME key. 
(T)opside
(U)nderside
(L)eft side
(R)ight side
(F)rontside
(B)ackside

### CODE REVIEW

**Comment by doug-moen** [comment]
Although topside and underside are good English, I am concerned that 'U' is  more commonly an abbreviation for "up" in graphics software. This might be a source of confusion.

How would you feel about using 'U' and 'D' instead, as abbreviations of up side and down side?

**Comment by doug-moen** [comment]
Code review: please replace tabs with spaces. Tab characters are not used in the Curv project.

Code review: please replace the magic numbers 0, 1, 2,... with named constants. Put an `enum` definition inside of `struct Viewer` that defines the constants.

**Comment by doug-moen** [comment]
Also, thank you for proposing and implementing this feature.

**Comment by TLC123** [comment]
Thank you for the feedback. I will make those changes.
I'm very happy i finally got around to learn C++ .

**Pull request merged**
