### PR TITLE
Adjustments to frag shader code

### PR DESCRIPTION
**Pull request by ivocavalcante**
* Adjusted max raymarching step (tmax), in order to increase viewer rendering distance (avoid object clipping when zooming out). With "tmax = 200", I was reaching the limit very easily.
* Adjusted viewer background color, in order to minimize eye strain by improving contrast with objects colours.

These changes might seen like personal preferences, so feel free to discard of you disagree.

### CODE REVIEW

**Comment by doug-moen** [comment]
I personally prefer a white background, so I don't want the one line change that hard codes the background colour to black.

I am thinking about adding a `-Obg=<colour>` command line option, as a first step to making the background colour user configurable.

I do want the change that sets tmax to 400. I consider this change a stop-gap, there must be a better way to implement sphere tracing.

**Comment by doug-moen** [comment]
I've pulled this code into the **adjust_frag_properties** branch of **doug-moen/curv**.

commit https://github.com/doug-moen/curv/pull/37/commits/dd89f08f16b1a2bce8216ccf1f4895c00bc772d5 has been added to the master branch (changes to geom/frag.cc). I kept the change that sets tmax to 400, and rolled back the change that sets the 3D background colour to black. (And I learned about `git cherry-pick` today.)

The `-Olazy` feature is still just in the branch, pending further evaluation.

In the future, I prefer each new feature to be in a separate branch and in a separate pull request.

**Comment by ivocavalcante** [comment]
Sorry Doug, my mistake. To be honest, I'm new to GitHub, still learning the
workflow.

I refused this branch to compile my "production" version of Curv, ended up
"poisoning" it. Also, updated lazy viewer branch with your newest commits -
this was prior to knowing that "pull requests" weren't statics, point in
time operations. Will keep branches clean, from now on.

Thanks!

Em ter, 11 de set de 2018 09:02, Doug Moen <notifications@github.com>
escreveu:

**Comment by ivocavalcante** [comment]
Great, Doug! Thanks.

**Pull request merged**
